version: 2.1
executors:
  unity-win:
    docker:
      - image: gableroux/unity3d:2019.2.16f1-windows
  main:
    docker:
      - image: circleci/python:3.7.3
jobs:
  build-win:
    executor: unity-win
    steps:
      - checkout # check out the code in the project directory
      - run: echo $UNITY_LICENSE | base64 --decode > .circleci/license.ulf
      - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile "./build/build-license.log" -manualLicenseFile .circleci/license.ulf || exit 0
      - run: /opt/Unity/Editor/Unity -batchmode -quit -nographics -silent-crashes -logFile "./build/build-win.log" -executeMethod Pipeline.BuildExecutor.BuildWindows
      - run: ls -a build
      - store_artifacts:
          path: build/Venturer_Windows
  
  test:
    executor: unity-win
    steps:
      - run: ls -a build

  deploy:
    executor: main
    steps:
      - run: zip build/Venturer_Windows.zip build/Venturer_Windows || exit 0
      - run: ls -a build
      - store_artifacts:
          path: build
          
workflows:
  version: 2
  build:
    jobs:
      - build-win
      - test
      - deploy