version: 2.1
     
config:
  unity-win: &unity-win
    docker:
      - image: gableroux/unity3d:2019.2.16f1-windows
  unity-webgl: &unity-webgl
    docker:
      - image: gableroux/unity3d:2019.2.16f1-webgl
  main: &main
    docker:
      - image: alpine:3.9.5
jobs:
  build-win:
    <<: *unity-win
    steps:
      - checkout
      - run:
          name: apt-get
          command: |
            apt-get -y update
            apt-get -y install zip
      - run:
          name: Load license
          command: |
            echo $UNITY_LICENSE | base64 --decode > .circleci/license.ulf
            /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile "./logs-win/license.log" -manualLicenseFile .circleci/license.ulf || exit 0
      - run: 
          name: Build
          command: |
            /opt/Unity/Editor/Unity -batchmode -quit -nographics -silent-crashes -logFile "./logs-win/build.log" -executeMethod Pipeline.BuildExecutor.BuildWindows
            ls -a build/venturer_windows
      - run: 
          name: Zip
          command: |
            zip -r venturer_win.zip build/venturer_windows
      - save_cache:
          key: venturer-win
          paths:
            - venturer_win.zip
            - logs-win
      - store_artifacts:
          path: logs-win
      - store_artifacts:
          path: venturer_win.zip
  build-webgl:
    <<: *unity-webgl
    steps:
      - checkout
      - run:
          name: apt-get
          command: |
            apt-get -y update
            apt-get -y install zip
      - run:
          name: Load license
          command: |
            echo $UNITY_LICENSE | base64 --decode > .circleci/license.ulf
            /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile "./logs-web/license.log" -manualLicenseFile .circleci/license.ulf || exit 0
      - run: 
          name: Build
          command: |
            /opt/Unity/Editor/Unity -batchmode -quit -nographics -silent-crashes -logFile "./logs-web/build.log" -executeMethod Pipeline.BuildExecutor.BuildWebGL
            ls -a build/venturer_web
      - run: 
          name: Zip
          command: |
            zip -r venturer_web.zip build/venturer_web
      - save_cache:
          key: venturer-web
          paths:
            - venturer_web.zip
            - logs-web
      - store_artifacts:
          path: logs-web
      - store_artifacts:
          path: venturer_web.zip
  test:
    <<: *unity-win
    steps:
      - checkout
      - run: ls -a || exit 0
  deploy:
    <<: *main
    steps:
      - restore_cache:
          keys:
            - venturer-win
            - venturer-web 
      - run:
          name: apt-get
          command: |
            apt-get -y update
            apt-get -y install unzip
            apt-get -y install curl
      - run:
          name: Publish zips
          command: |
            ls -a
      - run:
          name: Publish webgl
          command: |
            unzip venturer_web.zip web
            ls -a web
      - store_artifacts:
          path: logs-win
      - store_artifacts:
          path: logs-web
      - store_artifacts:
          path: venturer_win.zip
      - store_artifacts:
          path: venturer_web.zip
workflows:
  version: 2
  build:
    jobs:
      - build-win
      - build-webgl
      - test:
          requires:
            - build-win
            - build-webgl
      - deploy:
          requires:
            - test