version: 2.1
     
config:
  unity-win: &unity-win
    docker:
      - image: gableroux/unity3d:2019.2.16f1-windows
  unity-webgl: &unity-webgl
    docker:
      - image: gableroux/unity3d:2019.2.16f1-webgl
  main: &main
    docker:
      - image: alpine:3.9.5
jobs:
  build-win:
    <<: *unity-win
    steps:
      - checkout
      - run:
          name: Load license
          command: |
            echo $UNITY_LICENSE | base64 --decode > .circleci/license.ulf
            /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile "./logs/license-win.log" -manualLicenseFile .circleci/license.ulf || exit 0
      - run: 
          name: Build
          command: |
            /opt/Unity/Editor/Unity -batchmode -quit -nographics -silent-crashes -logFile "./logs/build-win.log" -executeMethod Pipeline.BuildExecutor.BuildWindows
            ls -a build/venturer_windows
      - persist_to_workspace:
          root: ~/project
          paths: 
            - build
            - logs
      - store_artifacts:
          path: logs
          
  build-webgl:
    <<: *unity-webgl
    steps:
      - checkout
      - run:
          name: Load license
          command: |
            echo $UNITY_LICENSE | base64 --decode > .circleci/license.ulf
            /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile "./logs/license-web.log" -manualLicenseFile .circleci/license.ulf || exit 0
      - run: 
          name: Build
          command: |
            /opt/Unity/Editor/Unity -batchmode -quit -nographics -silent-crashes -logFile "./logs/build-web.log" -executeMethod Pipeline.BuildExecutor.BuildWebGL
            ls -a build/venturer_web
      - persist_to_workspace:
          root: ~/project
          paths: 
            - build
            - logs
      - store_artifacts:
          path: logs
  test:
    <<: *main
    steps:
      - checkout
      - run: ls -a || exit 0
  deploy:
    <<: *main
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Download tools
          command: |
            apk update
            apk add p7zip
            apk add curl
      - run:
          name: Prepare zips
          command: |
            ls -a build/venturer_web/venturer
            ls -a build/venturer_windows
            7z a venturer_web.zip build/venturer_web/venturer/* || true
            7z a venturer_windows64.zip build/venturer_windows/* || true
      - run:
          name: Publish zips
          command: |
            ls -a
      - run:
          name: Publish webgl
          command: |
            ls -a build/venturer_web/venturer || exit 0
      - store_artifacts:
          name: Store logs
          path: logs
      - store_artifacts:
          name: Store windows zip
          path: venturer_windows64.zip
      - store_artifacts:
          name: Store web zip
          path: venturer_web.zip
workflows:
  version: 2
  build:
    jobs:
      - build-win
      - build-webgl
      - test:
          requires:
            - build-win
            - build-webgl
      - deploy:
          requires:
            - test