version: 2.1
     
config:
  unity-win: &unity-win
    docker:
      - image: gableroux/unity3d:2019.2.16f1-windows
  unity-webgl: &unity-webgl
    docker:
      - image: gableroux/unity3d:2019.2.16f1-webgl
   
jobs:
  build-win:
    <<: *unity-win
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Load license
          command: |
            echo $UNITY_LICENSE | base64 --decode > .circleci/license.ulf
            /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile "./logs-win/license.log" -manualLicenseFile .circleci/license.ulf || exit 0
      - run: 
          name: Build
          command: |
            /opt/Unity/Editor/Unity -batchmode -quit -nographics -silent-crashes -logFile "./logs-win/build.log" -executeMethod Pipeline.BuildExecutor.BuildWindows
            ls -a build/venturer_windows
      - store_artifacts:
          path: logs-win
  build-webgl:
    <<: *unity-webgl
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Load license
          command: |
            echo $UNITY_LICENSE | base64 --decode > .circleci/license.ulf
            /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile "./logs-web/license.log" -manualLicenseFile .circleci/license.ulf || exit 0
      - run: 
          name: Build
          command: |
            /opt/Unity/Editor/Unity -batchmode -quit -nographics -silent-crashes -logFile "./logs-web/build.log" -executeMethod Pipeline.BuildExecutor.BuildWebGL
            ls -a build/venturer_web
      - store_artifacts:
          path: logs-web
  test:
    <<: *unity-win
    steps:
      - run: tree -a build || exit 0
  deploy:
    <<: *unity-win
    steps:
      - run:
          name: apt-get
          command: |
            apt-get -y update
            apt-get -y install zip
            apt-get -y install tree
      - run:
          name: zip
          command: |
            mkdir delivery
            zip delivery/venturer_windows.zip build/venturer_windows || exit 0
            zip delivery/venturer_web.zip build/venturer_web || exit 0
            tree -a build
            tree -a delivery
      - store_artifacts:
          path: delivery 
workflows:
  version: 2
  build:
    jobs:
      - build-win
#      - build-webgl
      - test:
          requires:
            - build-win
#            - build-webgl
      - deploy:
          requires:
            - test