version: 2.1
executors:
  unity-win:
    docker:
      - image: gableroux/unity3d:2019.2.16f1-windows
jobs:
  build-win:
    executor: unity-win
    steps:
      - run: apt-get -y update
      - run: apt-get -y install zip
      - checkout # check out the code in the project directory
      - run: echo $UNITY_LICENSE | base64 --decode > .circleci/license.ulf
      - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile "./build/build-license.log" -manualLicenseFile .circleci/license.ulf || exit 0
      - run: /opt/Unity/Editor/Unity -batchmode -quit -nographics -silent-crashes -logFile "./build/build-win.log" -executeMethod Pipeline.BuildExecutor.BuildWindows
      - run: zip Venturer_Windows.zip Venturer_Windows
      - run: ls -a
      - store_artifacts:
          path: build
      - store_artifacts:
          path: build/Venturer_Windows

workflows:
  version: 2
  build:
    jobs:
      - build-win