version: 2.1
     
config:
  unity-win: &unity-win
    docker:
      - image: gableroux/unity3d:2019.3.14f1-windows
  unity-osx: &unity-osx
    docker:
      - image: gableroux/unity3d:2019.3.14f1-mac
  unity-linux: &unity-linux
    docker:
      - image: gableroux/unity3d:2019.3.14f1
  unity-webgl: &unity-webgl
    docker:
      - image: gableroux/unity3d:2019.3.14f1-webgl
  unity-android: &unity-android
    docker:
      - image: gableroux/unity3d:2019.3.14f1-android-update-2020-07-16-android
  main: &main
    docker:
      - image: alpine:3.9.5
jobs:
  build-win:
    <<: *unity-win
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            apt-get update
            apt-get install git-lfs
            git lfs install
            git lfs pull
            ls -lsR
      - run:
          name: Load license
          command: |
            echo $UNITY_LICENSE | base64 --decode > .circleci/license.ulf
            /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile "./logs/license-win.log" -manualLicenseFile .circleci/license.ulf || exit 0
      - run: 
          name: Build
          command: |
            /opt/Unity/Editor/Unity -batchmode -quit -nographics -silent-crashes -logFile "./logs/build-win.log" -executeMethod Pipeline.BuildExecutor.BuildWindows
            ls -a build/venturer_windows
      - persist_to_workspace:
          root: ~/project
          paths: 
            - build
            - logs
      - store_artifacts:
          path: logs
  build-osx:
    <<: *unity-osx
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            apt-get update
            apt-get install git-lfs
            git lfs install
            git lfs pull
            ls -lsR
      - run:
          name: Load license
          command: |
            echo $UNITY_LICENSE | base64 --decode > .circleci/license.ulf
            /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile "./logs/license-osx.log" -manualLicenseFile .circleci/license.ulf || exit 0
      - run: 
          name: Build
          command: |
            /opt/Unity/Editor/Unity -batchmode -quit -nographics -silent-crashes -logFile "./logs/build-osx.log" -executeMethod Pipeline.BuildExecutor.BuildOSX
            ls -a build/venturer_osx
      - persist_to_workspace:
          root: ~/project
          paths: 
            - build
            - logs
      - store_artifacts:
          path: logs
  build-linux:
    <<: *unity-linux
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            apt-get update
            apt-get install git-lfs
            git lfs install
            git lfs pull
            ls -lsR
      - run:
          name: Load license
          command: |
            echo $UNITY_LICENSE | base64 --decode > .circleci/license.ulf
            /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile "./logs/license-lin.log" -manualLicenseFile .circleci/license.ulf || exit 0
      - run: 
          name: Build
          command: |
            /opt/Unity/Editor/Unity -batchmode -quit -nographics -silent-crashes -logFile "./logs/build-lin.log" -executeMethod Pipeline.BuildExecutor.BuildLinux
            ls -a build/venturer_linux
      - persist_to_workspace:
          root: ~/project
          paths: 
            - build
            - logs
      - store_artifacts:
          path: logs
  build-webgl:
    <<: *unity-webgl
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            apt-get update
            apt-get install git-lfs
            git lfs install
            git lfs pull
            ls -lsR
      - run:
          name: Load license
          command: |
            echo $UNITY_LICENSE | base64 --decode > .circleci/license.ulf
            /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile "./logs/license-web.log" -manualLicenseFile .circleci/license.ulf || exit 0
      - run: 
          name: Build
          command: |
            /opt/Unity/Editor/Unity -batchmode -quit -nographics -silent-crashes -logFile "./logs/build-web.log" -executeMethod Pipeline.BuildExecutor.BuildWebGL
            ls -a build/venturer_web
      - persist_to_workspace:
          root: ~/project
          paths: 
            - build
            - logs
      - store_artifacts:
          path: logs
  build-android:
    <<: *unity-android
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            apt-get update
            apt-get install git-lfs
            git lfs install
            git lfs pull
            ls -lsR
      - run:
          name: Load license
          command: |
            echo $UNITY_LICENSE | base64 --decode > .circleci/license.ulf
            /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile "./logs/license-and.log" -manualLicenseFile .circleci/license.ulf || exit 0
      - run: 
          name: Build
          command: |
            /opt/Unity/Editor/Unity -batchmode -quit -nographics -silent-crashes -logFile "./logs/build-and.log" -executeMethod Pipeline.BuildExecutor.BuildAndroid
            ls -a build/venturer_android
      - persist_to_workspace:
          root: ~/project
          paths: 
            - build
            - logs
      - store_artifacts:
          path: logs
  test:
    <<: *main
    steps:
      - checkout
      - run:
          name: List files
          command: ls -lsR
      - run: ls -a || exit 0
  deploy:
    <<: *main
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Download tools
          command: |
            apk update
            apk add p7zip
            apk add curl
      - run:
          name: List files
          command: |
            ls -lsR
      - run:
          name: Zip web
          command: |
            ls -a build/venturer_web/venturer
            7z a venturer_web.zip build/venturer_web/venturer/* || true
      - run:
          name: Zip win64
          command: |
            ls -a build/venturer_windows
            7z a venturer_windows64.zip build/venturer_windows/* || true
      - run:
          name: Zip linux64
          command: |
            ls -a build/venturer_windows
            7z a venturer_linux64.zip build/venturer_linux/* || true
      - run:
          name: Zip osx
          command: |
            ls -a build/venturer_windows
            7z a venturer_osx.zip build/venturer_osx/* || true               
      - run:
          name: Publish zips
          command: |
            ls -a
      - run:
          name: Publish webgl
          command: |
            ls -a build/venturer_web/venturer || exit 0
      - store_artifacts:
          name: Store logs
          path: logs
      - store_artifacts:
          name: Store windows zip
          path: venturer_windows64.zip
      - store_artifacts:
          name: Store linux zip
          path: venturer_linux64.zip
      - store_artifacts:
          name: Store osx zip
          path: venturer_osx.zip 
      - store_artifacts:
          name: Store web zip
          path: venturer_web.zip
workflows:
  version: 2
  build:
    jobs:
      - build-win
      - build-linux
      - build-osx
      - build-webgl
      - build-android
      - test:
          requires:
            - build-win
            - build-webgl
            - build-osx
            - build-linux
            - build-android
      - deploy:
          requires:
            - test